### PR TITLE
Bump gmt from 6.0.0a16 to 6.0.0a17 and update other dependencies

### LINKED ISSUE #234: Fix binder online demo UnsatisfiableError at try.gmtpython.xyz
Hi there,

I'm starting an issue to fix the broken binder build at http://try.gmtpython.xyz. Appears to have been reported first at https://gitter.im/GenericMappingTools/gmt-python?at=5b76938b0825690ea2e125eb more than a year ago?!

**Full error message**

```
UnsatisfiableError: The following specifications were found to be in conflict:
    gmt=6.0.0a16
Use "conda info <package>" to see the dependencies for each package.
```

I'll open a pull request on https://github.com/GenericMappingTools/try-gmt-python to fix this (basically update the conda packages) using this [gist](https://gist.github.com/weiji14/f13a7fbde5855bbbeb036c4b1187f675) I made. Just tracking it here for better visibility :smiley:

### PR DESCRIPTION
**Pull request by weiji14**
**Description of proposed changes**

Updating the binder demo's dependencies to newer versions. Also update gmt-python version to https://github.com/GenericMappingTools/gmt-python/commit/2127ad0447ed28c2aff8e78cb628d54592209801.

Fixes https://github.com/GenericMappingTools/gmt-python/issues/234

Test using https://mybinder.org/v2/gh/weiji14/try-gmt-python/432a66fbd9138220422aba24fee14d84b5a48325?filepath=try-gmt-python.ipynb

### CODE REVIEW

**Comment by seisman** [comment]
Since GMT 6.0.0rc1 has been released, maybe we should update the PR and make the online demo work again.

**Comment by weiji14** [comment]
I was thinking of the same actually. Should we rename the repository name to 'try-pygmt' first though?

**Comment by seisman** [comment]
Jupyter can also run bash scripts. Maybe we can rename it to "try-gmt" and host the website at try.generic-mapping-tools.org. Thus users can try both the GMT command-line and PyGMT in one site.

**Comment by weiji14** [comment]
> Jupyter can also run bash scripts. Maybe we can rename it to "try-gmt" and host the website at try.generic-mapping-tools.org.

There's actually such a demo at https://github.com/GenericMappingTools/gmt6demo.

Edit: Tested the demo using https://mybinder.org/v2/gh/GenericMappingTools/gmt6demo/master?filepath=demo.ipynb, it's broken with `gmt: error while loading shared libraries: liblapack.so.3: cannot open shared object file: No such file or directory` so we'll need to update it if we're gonna move everything to that repository.

> Thus users can try both the GMT command-line and PyGMT in one site.

Why you could even go as far as include the Julia and Matlab wrappers in one whole repository!

**Comment by seisman** [comment]
> > Jupyter can also run bash scripts. Maybe we can rename it to "try-gmt" and host the website at try.generic-mapping-tools.org.
> 
> There's actually such a demo at https://github.com/GenericMappingTools/gmt6demo.

I noticed that repo. Actually that's why I want to have all in one place, so we don't need to maintain two or more similar repositories.

**Comment by weiji14** [comment]
Ok, then let's move everything to that repository then. We should archive this repository and put a note on the main README.md (in case there's people coming to this repository from the Scipy 2018 video for example).

**Comment by seisman** [comment]
@leouieda What do you think about it?

**Comment by leouieda** [comment]
I agree with both of you. We should update and concentrate everything on a single repo with a binder link from try.generic-mapping-tools.org  We can have Julia, bash and Python at least.

**Comment by leouieda** [comment]
I would archive this repository and the gmt6demo (which was for an AGU meeting) and make a new `try-gmt` repo.

**Pull request closed without merging**
